# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _svlock
else:
    import _svlock

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def svlock_is_initialized(index=0, pid=0, tid=0, duration=0):
    return _svlock.svlock_is_initialized(index, pid, tid, duration)

def svlock_get_initialized(index=0, pid=0, tid=0, duration=0):
    return _svlock.svlock_get_initialized(index, pid, tid, duration)

def svlock_set_initialized(index=0, value=0, pid=0, tid=0, duration=0):
    return _svlock.svlock_set_initialized(index, value, pid, tid, duration)

def svlock_shm_open():
    return _svlock.svlock_shm_open()

def svlock_init_index(index=0, value=0, pid=0, tid=0, duration=0):
    return _svlock.svlock_init_index(index, value, pid, tid, duration)

def svlock_init(value=0, pid=0, tid=0, duration=0):
    return _svlock.svlock_init(value, pid, tid, duration)

def svlock_acquire(index=0, pid=0, tid=0, duration=0):
    return _svlock.svlock_acquire(index, pid, tid, duration)

def svlock_release(index=0, pid=0, tid=0, duration=0):
    return _svlock.svlock_release(index, pid, tid, duration)

def svlock_getvalue(index=0, pid=0, tid=0, duration=0):
    return _svlock.svlock_getvalue(index, pid, tid, duration)

def svlock_get_value(index=0, pid=0, tid=0, duration=0):
    return _svlock.svlock_get_value(index, pid, tid, duration)

def svlock_get_count(index=0, pid=0, tid=0, duration=0):
    return _svlock.svlock_get_count(index, pid, tid, duration)

def svlock_close(index=0, pid=0, tid=0, duration=0):
    return _svlock.svlock_close(index, pid, tid, duration)

def svlock_unlink():
    return _svlock.svlock_unlink()

def svlock_release_all():
    return _svlock.svlock_release_all()

def svlock_release_all_index(index=0, pid=0, tid=0, duration=0):
    return _svlock.svlock_release_all_index(index, pid, tid, duration)

def svlock_close_all():
    return _svlock.svlock_close_all()

def svlock_cleanup():
    return _svlock.svlock_cleanup()

def svlock_shm_close():
    return _svlock.svlock_shm_close()

